### ISSUE TITLE
Add script to reverse DMA actions

### ISSUE THREAD

**Issue by LiChunHua535** [sir-noancoare/dmawatch#1]
For students that wish to run apps without completely disabling the DMA or manually going into the Group Policy to enable running apps normally (which gets reset every time filewave activates), a script (.bat file most likely) can be made to run all the commands to reverse the effects of the DMA. LGPO.exe can be used to change Group Policy along with gpupdate /force, this is already what the DMA uses. 
To do this, you can just gather all of the files in the filewave/scripts directory, most scripts should have their inverse script in there (might be helpful to remove the folder structure first), and for those that don't just change the command in the file. This method will be foolproof as once the script is run (which will preferably delete LGPO.exe and ntrights.exe, along with all the scripts in the FileWave ProgramData folder to stop it from automatically fixing itself, the filewave process then can be killed after that, then a restart to apply things), and as to reverse simply restart the device and use the verify button on filewave to restore all settings.

Regards, Chun Hua (not revealing class to remain anonymous)

(also, fix the dmadestroyer docm file. the password is not up to date.)

**Comment by sir-noancoare** [comment]
Will do soon, if the new and enhanced dma is still filewave(highly unlikely). I'll close this issue once I'm done, or if the new dma is not filewave

**Comment by sir-noancoare** [comment]
I'm just going to close this
